version: '3.8'

services:
  frontend-cmpc:
    build: ./frontend-cmpc
    ports:
      - "3003:3003"
    depends_on:
      - backend_cmpc

  backend_cmpc:
    build: ./backend_cmpc
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432   # dentro del contenedor es 5432
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: postgres
      DB_SCHEMA: cmpc

  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"   # mapear 5433 host al 5432 contenedor
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

volumes:
  pgdata:
